export const ESC_KEYCODE = 27;
export const API_URL = 'https://norma.nomoreparties.space/api';

export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const ADD_MODAL_INGREDIENT = 'ADD_MODAL_INGREDIENT';
export const REMOVE_MODAL_INGREDIENT = 'REMOVE_MODAL_INGREDIENT';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const ADD_BUN = 'ADD_BUN';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

export const CHANGE_POSITIONS = 'CHANGE_POSITIONS';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_FAILED = 'AUTH_FAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REFRESH_TOKEN_SUCCESS= 'REFRESH_TOKEN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD_ENTER = 'RESET_PASSWORD_ENTER';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';