export const ESC_KEYCODE: string = 'Escape';
export const API_URL: string = 'https://norma.nomoreparties.space/api';
export const WS_URL: string = 'wss://norma.nomoreparties.space/orders';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const ADD_MODAL_INGREDIENT: 'ADD_MODAL_INGREDIENT' = 'ADD_MODAL_INGREDIENT';
export const REMOVE_MODAL_INGREDIENT: 'REMOVE_MODAL_INGREDIENT' = 'REMOVE_MODAL_INGREDIENT';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';

export const CHANGE_POSITIONS: 'CHANGE_POSITIONS' = 'CHANGE_POSITIONS';

export const AUTH_REQUEST: 'AUTH_REQUEST' = 'AUTH_REQUEST';
export const AUTH_FAILED: 'AUTH_FAILED' = 'AUTH_FAILED';
export const REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS' = 'REGISTRATION_SUCCESS';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const GET_USER: 'GET_USER' = 'GET_USER';
export const UPDATE_USER: 'UPDATE_USER' = 'UPDATE_USER';
export const FORGOT_PASSWORD: 'FORGOT_PASSWORD' = 'FORGOT_PASSWORD';
export const RESET_PASSWORD_ENTER: 'RESET_PASSWORD_ENTER' = 'RESET_PASSWORD_ENTER';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';

export const REGISTRATION_FIELDS_REQUIRED: string = 'Почта, пароль и имя - обязательно для заполнения';
export const NAME_OCCUPIED: string = 'Имя уже занято';
export const WRONG_EMAIL_CODE: string = 'Неправильный код из письма';
export const INCORRECT_EMAIL_OR_PASSWORD: string = 'Неправильный логин или пароль';
export const INGREDIENT_NOT_FOUND: string = 'Не найден ингредиент для добавления в конструктор. Перезагрузите страницу';
export const DEFAULT_ERROR: string = 'Произошла ошибка';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';